Add the plugin development documentation
PyMoDAQ/PyMoDAQ pull request #118
Opened 2023-06-21 14:27 UTC by quantumm

This is a tutorial for the plugin development based on the example of the [PI E870 plugin](https://github.com/PyMoDAQ/pymodaq_plugins_physik_instrumente/pull/4).

2023-06-21 14:28 UTC, quantumm commented
It has been sent to the v3 branch because there is probably some minor changes to make it v4 compatible.

2023-06-21 14:29 UTC, quantumm commented
Have a good reading ;)

2023-06-22 12:01 UTC, seb5g commented
That's quite a bit of a book!! It will be a very valuable piece of documentation for beginners.

I don't have much comment at the moment except a few below:

1. The first concerns the vocabulary used concerning pymodaq's plugin. Initially they were only for instruments, but as it turns out they are now also used for pid models, extensions, extending functionalities (through factory patterns)... That is why I introduced a dedicated vocabulary concerning those:

![image](https://github.com/PyMoDAQ/PyMoDAQ/assets/6609955/b293cc58-0d44-43bc-bfd0-0609cc9a88ff)

I think therefore we could speak about a pymodaq plugin as a package giving new functionalities to pymodaq and refer to the type of functionalities we are talking about:

- instrument 
- extensions
- pid models
- factories (not ready yet)

a plugin with a manufacturer name will be considered as an *instrument plugin* but one could also consider a plugin named:
*pymodaq_plugins_attolab* that contains your specific pid models and factories (for instance specific exports from hdf5 only you are using)
or a plugin called:
*pymodaq_plugins_console* that enables a ipython console from the dahboard...

Do you think you could talk about this in your tutorial? 

2. Concerning the third party libraries (pylablib, instrumental-lib, ...)
You should maybe tell what they are good at. You already said quite a bit about pylablib so maybe you should say that instrumental-lib is particularly good to create drivers from dll written from C where one have the header file. For autoprocessing of the functions signature... And I like you to mention pymeasure I'm being more involved with. This libray is very efficient for all instruments that communicate through ascii commands (pyvisa basically) and make drivers very easy to use and develop. I just produced one for the elliptec thorlabs piezo drivers in a day!! I'm also going to invite those guys to the pymodaq's days!

3. Maybe say that your example is one dealing with C dlls but that a big zoology exists (ascci commands, C/C++ dlls (using instrumental-lib or ctypes or manufacturer wrappers) but also .net libraries using pythonnet...

Thanks a lot for this work, we will publish it in the v3 after you modified your text according to what i just wrote and then port it to the v4 as is. In this v4 (pymodaq_dev branch actually), the documentation layout is quite different and I'll make a specific tutorial entry.

2023-06-27 16:31 UTC, quantumm commented
I think I have implemented all the corrections you asked.

Let me know if this is ok ;)

2023-06-28 14:22 UTC, seb5g commented on docs/src/usage/plugin_development.rst
> +Now that PyMoDAQ is installed and you have activated your environment (the lign of your terminal should start with *(pmd_dev)*), we will try to install the PI instrument plugin with the plugin manage
replace lign by line

2023-06-28 14:24 UTC, seb5g approved these changes

2023-06-28 14:29 UTC, seb5g requested changes
please change the bits about the label/reference

2023-06-30 09:20 UTC, quantumm commented on docs/src/usage/plugin_development.rst
Done in f05aaadf70ef0be4245c76178e70ae6d91461f4e.

2023-06-30 13:01 UTC, seb5g approved these changes

2023-06-30 13:02 UTC, merged